### ISSUE TITLE
Combo Trials not working?

### ISSUE THREAD

**Issue by BlueSkyGuyBSG** [grimkor/GrimbaHack#13]
When I go to select combo trials and I am loaded into the character select screen the game won't let me move the curser to other characters besides random select. But even when choosing random select the game crashes. 
![PW Screenshot](https://github.com/grimkor/GrimbaHack/assets/172748163/ce43e729-7e2e-427a-b73a-904d6460c997)

**Comment by grimkor** [comment]
Hey @BlueSkyGuyBSG could you make sure in the `<Game Directory>/BepInEx/plugins/combos` folders that there are combo files inside each one? They will be `*.json` files. My first assumption is that the zip file did not extract correctly and the mod cannot see those files.

**Comment by grimkor** [comment]
@BlueSkyGuyBSG do you still require assistance with this?
