### ISSUE TITLE
Trey Combo Trial Crash

### ISSUE THREAD

**Issue by Ferns101** [grimkor/GrimbaHack#14]
I booted up the game went into Combo Trials with Trey, and picked the Universal Loops trial. I realized it was 60fps instead of 120fps so I went back and set the game to 120fps Exclusive Fullscreen. I then went back to the same trial. I did the trial on my first attempt until I got to Pyramidas, where I got the j.5H5S off, dashed forward twice, and then the game crashed.
[ErrorLog.log](https://github.com/user-attachments/files/15843778/ErrorLog.log)
[LogOutput.log](https://github.com/user-attachments/files/15843780/LogOutput.log)

**Comment by Ferns101** [comment]
For clarity, this is on the (Expert) Universal Legloops trial. I had to trim the clip down to fit it here, but the crash happens after the second dash after Pyramidas. However, sometimes it doesn't occur as I had to restart the game a few times to have this glitch happen again consistently.

[LogOutput.log](https://github.com/user-attachments/files/15844377/LogOutput.log)
[ErrorLog.log](https://github.com/user-attachments/files/15844378/ErrorLog.log)

https://github.com/grimkor/GrimbaHack/assets/172853020/205d89f8-c9c9-46e3-9ec0-ec407f1ded01

**Comment by grimkor** [comment]
Hey @Ferns101 did you definitely copy the log files before booting the game back up? The mod clears the logs every time the game loads. Nothing in the logs suggests anything went wrong.

**Comment by Ferns101** [comment]
Yeah. Both times I copied the files right after the crash happened.

**Comment by grimkor** [comment]
To be sure did you try this without the mod and can you replicate it
without?

**Comment by Ferns101** [comment]
I tried doing the same combo in training mode the exact same way and it doesn't cause a crash. Nor has the game ever crashed during Pyramidas before I installed the mod. The crash only seems to happen in the combo trial.

**Comment by grimkor** [comment]
Hey Ferns I went through a load of tests with Rizu earlier this week and we've determined this is an issue with the game and not the mod, the setup you've shown does have a chance to crash the game with a vanilla installation of the game.

As a result of this I will close the issue, there is nothing I can do to save this.
