### ISSUE TITLE
-Game freezing upon binding playback button-

### ISSUE THREAD

**Issue by kdawgspillz** [grimkor/GrimbaHack#19]
-Attempting to bind L1 on my Razer Panthera to the playback button.

https://github.com/user-attachments/assets/f6cb095c-d350-45e2-8f06-8e27625f4df8

**Comment by grimkor** [comment]
Can you repeat the steps so it crashes and uploads the logs from the `<game directory>/BepInEx/*.log` please? I need that to get started.

Thank you for the video and report.
